---
title: "Is_Cereal_Killer"
author: "Sophia Waxman"
date: "2025-11-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())

library(RKaggle)
library(tidyverse)
library(pwr)
library(ggplot2)
library(GGally)


data <- get_dataset("crawford/80-cereals") %>% na.omit() %>% mutate("HotCold" = ifelse(type == "C", 1, 0))
data
```

```{r "descriptive statistics"}
#How many cereals does each manufacturer make?
table(data$mfr)

#How many cereals are hot vs. cold?
table(data$type)

#How heavy are the cereals on average on each shelf?
shelf1 <- subset(data, shelf == "1")
shelf2 <- subset(data, shelf == "2")
shelf3 <- subset(data, shelf == "3")

mean(shelf1$weight/shelf1$cups)
mean(shelf2$weight/shelf2$cups)
mean(shelf3$weight/shelf3$cups)

#Which cereal has the highest amount of sugar per weight (highest sugar density)?
data <- mutate(data, sugarden = data$sugars/data$weight)
data$name[which.max(data$sugarden)]

#Which cereal manufacturer produces the most fibrous cereal on average?
A <- subset(data, mfr == "A")
G <- subset(data, mfr == "G")
K <- subset(data, mfr == "K")
N <- subset(data, mfr == "N")
P <- subset(data, mfr == "P")
Q <- subset(data, mfr == "Q")
R <- subset(data, mfr == "R")

DF <- data.frame(meanfiber = c(mean(A$fiber), mean(G$fiber), mean(K$fiber), mean(N$fiber), 
                   mean(P$fiber), mean(Q$fiber),mean(R$fiber)), 
                 row.names = c("A", "G", "K", "N", "P", "Q", "R"))

rownames(DF)[which.max(DF$meanfiber)]
```



```{r "research question1"}
# Which cereals are the least healthy? 
data2 <- data %>%
  mutate(
    fiber_z = scale(fiber),
    protein_z = scale(protein),
    vitamins_z = scale(vitamins),
    sugars_z = scale(sugars),
    calories_z = scale(calories),

    health_score = ((fiber_z + protein_z + vitamins_z) - (sugars_z + calories_z))/cups
  )

arranged <- data2 %>%
  arrange(desc(health_score)) %>%
  select(name, mfr, cups, fiber, protein, vitamins, sugars, calories, health_score)

head(arranged, 5)
tail(arranged, 5)


```



```{r "research question2"}
# Does the rating of the cereal differ by manufacturer?
m2 <- lm(rating ~ mfr, data=data)

anova2 <- aov(m2)
summary(anova2)

TukeyHSD(anova2)
ggplot(data, aes(x = mfr, y = rating, fill = mfr)) +
  geom_boxplot(alpha = 0.7) +
  theme_minimal() +
  labs(title = "Cereal Ratings by Manufacturer",
       x = "Manufacturer",
       y = "Consumer Rating")

#Outliers
# Cook's distance
cooks <- cooks.distance(anova2)

# Find the highest value
outlier_index = which.max(cooks)

# View that observation
data[outlier_index, c("name", "mfr", "rating", "sugars", "calories")]

# Optional plot
plot(cooks, type = "h",
     main = "Cook's Distance for Each Cereal",
     ylab = "Cook's Distance")
abline(h = 4 / length(cooks), col = "red", lty = 2)

# Remove the outlier
data_no_outlier <- data[-outlier_index, ]

# Re-run ANOVA
anova_no_outlier <- aov(rating ~ mfr, data = data_no_outlier)
summary(anova_no_outlier)

# Compare with original model
summary(anova2)

ggplot(data_no_outlier, aes(x = mfr, y = rating, fill = mfr)) +
  geom_boxplot(alpha = 0.7) +
  theme_minimal() +
  labs(
    title = "Cereal Ratings by Manufacturer (Outlier Removed)",
    x = "Manufacturer",
    y = "Consumer ReportsRating"
  )

```

```{r "more research questions"}
#Are sugar and fiber inversely correlated? (regression model)
suga <- data$sugars != "-1"
sugar <-data$sugars[suga]
fiber <- data$fiber[suga]
cor.test(sugar, fiber)

#Is the type of cereal correlated with potassium content? (regression model)
pot <- data$potass != "-1"
potato <-data$potass[pot]
hotcold <- data$HotCold[pot]
cor.test(data$HotCold, data$potass)

```